
editor.cursor-shape.insert = "bar"
editor.cursor-shape.normal = "block"
editor.cursor-shape.select = "underline"
editor.file-picker.hidden = false
editor.line-number = "relative"
editor.lsp.display-inlay-hints = true
editor.true-color = true
theme = "modus_vivendi"

